### ISSUE TITLE
GET search failed: cannot get X-Ratelimit-Limit from header

### ISSUE THREAD

**Issue by sklinkert** [kosa3/pexels-go#2]
Hi, 

First of all: Thanks for working on this client!

When doing `Search()` I often receive the following error:

`GET search failed: cannot get X-Ratelimit-Limit from header`

Is this ratelimit stuff really necessary or should we maybe expect responses without this header?

Full code example:

```go
		photoResponse, err := image.client.PhotoService.Search(ctx, &pexels.PhotoParams{
			Query: "finance",
			Page:  1,
		})
		if err != nil {
			return images, err
		}
```

**Comment by kosa3** [comment]
@sklinkert 

HI,

Thanks for using this client library.
The `X-Ratelimit-Limit` is always included in the 2xx response header of the pexels api.
https://www.pexels.com/api/documentation/#statistics

Is there something I can't reproduce in my environment but not included in the 2xx response headers in yours?

If this is occurring in your environment, the code to check RateLimit may not be necessary.
Also, official client libraries such as pexels-javascript, pexels-ruby do not check RateLimit. Therefore, RateLimit checking in pexels-go may not be necessary either.

**Comment by sklinkert** [comment]
Hi @kosa3,

I just double-checked it and I receive a `200 OK`:

```
RESPONSE: 200
Headers: map[Access-Control-Allow-Origin:[*] Alt-Svc:[h3=":443"; ma=86400, h3-29=":443"; ma=86400] Cache-Control:[max-age=0, private, must-revalidate] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[6f6903b16ea744fe-TXL] Content-Type:[application/json; charset=utf-8] Date:[Mon, 04 Apr 2022 09:28:32 GMT] Etag:[W/"7b4ceea4aa12dafd5fe1f63dcc4a9ec4"] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Server:[cloudflare] Set-Cookie:[__cf_bm=GiTprZPW4NyTstlUblpGwYCZkg5p4RXlJwfhXX_UH68-1649064512-0-AVQ5e2rL9osMYA3Z1qyhQdz4UvZfT5NA2JF0sqvlZj6tud0rxRu4ZO1DaP5wZ53jMw1BN56uwYhfA1yqzeavENk=; path=/; expires=Mon, 04-Apr-22 09:58:32 GMT; domain=.pexels.com; HttpOnly; Secure; SameSite=None] Vary:[Accept-Encoding] X-Frame-Options:[SAMEORIGIN] X-Ratelimit-Remaining:[20000] X-Request-Id:[80c20f21-4973-4f9f-8b22-672999657010] X-Runtime:[0.083814] X-Server:[anteater]]
```

When I disable the call to `RateLimitFromHeader()` it just works and I get images. So we should either remove the code or make it aware of missing header fields.

**Comment by kosa3** [comment]
@sklinkert 

Thanks.

I just tried a few times and confirmed the same problem.

```
map[Access-Control-Allow-Origin:[*] Alt-Svc:[h3=":443"; ma=86400, h3-29=":443"; ma=86400] Cache-Control:[max-age=0, private, must-revalidate] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[6f692f346ee03438-NRT] Content-Type:[application/json; charset=utf-8] Date:[Mon, 04 Apr 2022 09:58:15 GMT] Etag:[W/"1f7a63dba0a6470fb27edbabb7859ffe"] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Server:[cloudflare] Set-Cookie:[__cf_bm=dqVMWtpQlD2ynMFV.XMhE85BoDf13X1wsyiop7RSKAA-1649066295-0-AX2spPQ36BhU0NQlhfwJ17zjdKz1letpCNmDPFWJBzdF/bhcsphkkcnth/1UM5nujKMx5lTQ/6Et8v447w5yBnI=; path=/; expires=Mon, 04-Apr-22 10:28:15 GMT; domain=.pexels.com; HttpOnly; Secure; SameSite=None] Vary:[Accept-Encoding] X-Frame-Options:[SAMEORIGIN] X-Ratelimit-Remaining:[20000] X-Request-Id:[40e86b96-b26b-4bcc-a4c9-a1c4a4742529] X-Runtime:[0.722962] X-Server:[anteater]]
```

The return value of the number of limits is also strange and unreliable, so I will remove the code.

**Comment by kosa3** [comment]
@sklinkert 

Fixed code has been released.
Please confirm with v0.0.3.

https://github.com/kosa3/pexels-go/releases/tag/v0.0.3

**Comment by sklinkert** [comment]
Works for me, thanks!
