### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by ErikTMA** [kosa3/pexels-go#5]
Not sure if there's a new update to pexels api or what, but I have recently started getting 401 errors on all requests.

According to their API documentation, we need to use "Authorization: <key>" but you are injecting "Authorization: Bearer <key>" to the header.

Using bearer token does not work on postman either, but just adding the Authorization header key with the key as value works fine. I assume it's an update, since it worked fine a couple of weeks ago.

**Comment by kosa3** [comment]
Thanks for the report, I can confirm that it is 401 for Bearer certification as reported.
I will fix this issue.

**Comment by kosa3** [comment]
A fix was released in the latest v0.0.4.

https://github.com/kosa3/pexels-go/releases/tag/v0.0.4
